version: "3.0"
services:
  app:
    build:
      context: ./
      dockerfile: fpm.Dockerfile
    volumes:
      - ./php.ini:/etc/php/php.ini
      - ./src:/app
    command: "sh fpm-start.sh"
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./src:/app
      - ./site.conf:/etc/nginx/site.conf
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: core
    command: --default-authentication-plugin=mysql_native_password
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080